import Head from 'next/head';
import Link from 'next/link';

export const metadata = {
  title: 'Next 13',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <header>
        <h1>Next13 - Header - Root Layout</h1>
      </header>
      <main>{children}</main>
      <footer>
        <h4>NextJs 13 - Footer - Root Layout</h4>
        <Link href="/">Back to Home</Link>
      </footer>
    </>
  );
}
